"""
Persistent device property management for ACE devices.
Maps device IDs (USB location) to persistent configuration (colors, materials, temps).
"""

import os
import time
import logging
import configparser
import json

from .device_discovery import AceDeviceDiscovery


class AceDeviceMapper:
    """
    Manages persistent device properties mapped by device ID (USB location).
    Gate offsets are dynamically assigned at runtime based on currently connected devices.
    Device properties (colors, materials, temps) persist with the device regardless of gate assignment.
    """

    def __init__(self, config_path):
        """
        Initialize device mapper.

        Args:
            config_path: Path to configuration file for persisting device mappings
        """
        self.config_path = config_path
        self.device_map = {}  # device_id -> {port, usb_location, properties, last_seen, last_gate_offset}
        self.load()

    def load(self):
        """Load device map and properties from file"""
        if not os.path.exists(self.config_path):
            return

        parser = configparser.ConfigParser()
        parser.read(self.config_path)

        # Load device metadata from main section (backward compatible)
        if parser.has_section('ace_device_map'):
            for device_id_raw, value in parser.items('ace_device_map'):
                if device_id_raw.startswith('#'):
                    continue
                # Sanitize device_id when loading (handles migration from old unsanitized IDs)
                device_id = AceDeviceDiscovery.sanitize_device_id(device_id_raw)
                parts = [p.strip() for p in value.split(',')]
                if len(parts) >= 2:
                    self.device_map[device_id] = {
                        'port': parts[0],
                        'usb_location': parts[3] if len(parts) > 3 else '',
                        'last_seen': int(parts[2]) if len(parts) > 2 else 0,
                        'last_gate_offset': int(parts[1]) if len(parts) > 1 else 0,  # Informational only
                        'properties': {}
                    }

        # Load device-specific properties from individual sections
        for section in parser.sections():
            if section.startswith('device:'):
                device_id_raw = section[7:]  # Remove 'device:' prefix
                # Sanitize device_id when loading (handles migration from old unsanitized IDs)
                device_id = AceDeviceDiscovery.sanitize_device_id(device_id_raw)
                if device_id not in self.device_map:
                    self.device_map[device_id] = {
                        'port': '',
                        'usb_location': '',
                        'last_seen': 0,
                        'last_gate_offset': 0,
                        'properties': {}
                    }

                # Load properties
                props = {}
                for key, value in parser.items(section):
                    try:
                        # Try to parse as JSON for lists
                        props[key] = json.loads(value)
                    except (json.JSONDecodeError, ValueError):
                        # Store as string if not JSON
                        props[key] = value

                self.device_map[device_id]['properties'] = props

    def save(self):
        """Save device map and properties to file"""
        parser = configparser.ConfigParser()

        # Save main device mapping section
        parser.add_section('ace_device_map')
        for device_id, info in sorted(self.device_map.items()):
            # Sanitize device_id for use as config option name
            safe_id = AceDeviceDiscovery.sanitize_device_id(device_id)
            value = f"{info['port']}, {info['last_gate_offset']}, {int(time.time())}, {info.get('usb_location', '')}"
            parser.set('ace_device_map', safe_id, value)

        # Save device-specific properties in separate sections
        for device_id, info in sorted(self.device_map.items()):
            if info.get('properties'):
                # Sanitize device_id for use as section name
                safe_id = AceDeviceDiscovery.sanitize_device_id(device_id)
                section_name = f'device:{safe_id}'
                parser.add_section(section_name)
                for prop_key, prop_value in info['properties'].items():
                    # Serialize lists/dicts as JSON
                    if isinstance(prop_value, (list, dict)):
                        value_str = json.dumps(prop_value)
                    else:
                        value_str = str(prop_value)
                    parser.set(section_name, prop_key, value_str)

        # Write with header comment
        with open(self.config_path, 'w') as f:
            f.write('# Auto-generated by ACE Manager - DO NOT EDIT MANUALLY\n')
            f.write('# This file stores device properties by USB port location\n')
            f.write('# Gate offsets are dynamically assigned based on currently connected devices\n')
            f.write('# Device properties (colors, materials, temps) persist with the device\n\n')
            parser.write(f)

    def update_device(self, device_id, port, usb_location=None, current_gate_offset=None):
        """Update or add a device mapping"""
        if device_id not in self.device_map:
            self.device_map[device_id] = {
                'port': port,
                'usb_location': usb_location or '',
                'last_seen': int(time.time()),
                'last_gate_offset': current_gate_offset if current_gate_offset is not None else 0,
                'properties': {}
            }
        else:
            self.device_map[device_id]['port'] = port
            self.device_map[device_id]['usb_location'] = usb_location or self.device_map[device_id].get('usb_location', '')
            self.device_map[device_id]['last_seen'] = int(time.time())
            if current_gate_offset is not None:
                self.device_map[device_id]['last_gate_offset'] = current_gate_offset

    def get_device_properties(self, device_id):
        """Get properties for a device"""
        return self.device_map.get(device_id, {}).get('properties', {})

    def update_device_properties(self, device_id, properties):
        """Update properties for a device"""
        if device_id in self.device_map:
            self.device_map[device_id]['properties'].update(properties)
        else:
            logging.warning(f"ACE Mapper: Tried to update properties for unknown device {device_id}")

    def get_device_info(self, device_id):
        """Get full device info"""
        return self.device_map.get(device_id, {})

    def get_all_devices(self):
        """Get all known devices"""
        return self.device_map.copy()

    def find_device_by_port(self, port):
        """Find device ID by current port"""
        for device_id, info in self.device_map.items():
            if info['port'] == port:
                return device_id
        return None
